### ISSUE TITLE
useMatch sur route wiki

### ISSUE THREAD

**Issue by ccreusat** [OPEN-ENT-NG/wiki#43]
Remettre useMatch comme il était dans `routes/wiki/index.tsx`

Coquille de ma part, il faut que les verifs avec `match` soient `match` aux 2 endroits et non `!match` donc useMatch renvoie un objet si on est sur la route emptyscreen

@Headan je parle de ton dernier commit 

Merci

**Comment by Headan** [comment]
Je refait un commit je sais pas si j'ai compris exactement ce que tu voulais car `const match = useMatch('/id/:wikiId');` renvoie à chaque fois une valeur null quand on est sur une url http://localhost:4200/id/ed0bc6ae-4cf2-408e-9d3a-b6c91a9f701f ce qui me semble bizarre ...

**Comment by ccreusat** [comment]
Dans le code, tu as 2 fois `!match`. La condition est mauvaise, c'est une coquille que j'ai laissé 

Ça doit être `match` dans clsx et au niveau du ternary pour afficher l'emptyscreen

Le hook doit renvoyer un objet quand on est sur la page de l'emptyscreen. Sinon, il doit renvoyer `null` si on est sur une page

**Comment by ccreusat** [comment]
@Headan c'est ok maintenant sauf le 2e `!match`qui est encore là, ligne 122

Ça doit être `match` sans le !

Merci 😄
